package com.banking.fraud_detection_service.controller;

import com.banking.fraud_detection_service.controller.dto.FraudAlertResponse;
import com.banking.fraud_detection_service.controller.dto.FraudStatsResponse;
import com.banking.fraud_detection_service.controller.dto.UpdateAlertStatusRequest;
import com.banking.fraud_detection_service.service.FraudAlertService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/v1/fraud")
@RequiredArgsConstructor
@Tag(name = "Fraud Alerts", description = "Endpoints for managing and querying fraud alerts generated by the rule engine")
public class FraudAlertController {

    private final FraudAlertService fraudAlertService;

    @GetMapping("/alerts")
    @Operation(
            summary = "Get all fraud alerts",
            description = "Returns a paginated list of all fraud alerts sorted by creation date descending"
    )
    public ResponseEntity<Page<FraudAlertResponse>> getAllAlerts(
            @Parameter(description = "Page number, starting from 0") @RequestParam(defaultValue = "0") int page,
            @Parameter(description = "Number of alerts per page") @RequestParam(defaultValue = "20") int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by("createdAt").descending());
        return ResponseEntity.ok(fraudAlertService.getAllAlerts(pageable));
    }

    @GetMapping("/alerts/{id}")
    @Operation(
            summary = "Get fraud alert by ID",
            description = "Returns a single fraud alert by its ID. Returns 404 if not found"
    )
    public ResponseEntity<FraudAlertResponse> getAlertById(
            @Parameter(description = "Fraud alert ID") @PathVariable Long id) {
        return ResponseEntity.ok(fraudAlertService.getAlertById(id));
    }

    @GetMapping("/alerts/account/{accountId}")
    @Operation(
            summary = "Get fraud alerts by account",
            description = "Returns all fraud alerts associated with a specific account ID"
    )
    public ResponseEntity<List<FraudAlertResponse>> getAlertsByAccount(
            @Parameter(description = "Account ID to search alerts for") @PathVariable String accountId) {
        return ResponseEntity.ok(fraudAlertService.getAlertsByAccount(accountId));
    }

    @PatchMapping("/alerts/{id}/status")
    @Operation(
            summary = "Update alert status",
            description = "Updates the status of a fraud alert. Valid statuses are OPEN, REVIEWED, DISMISSED"
    )
    public ResponseEntity<FraudAlertResponse> updateAlertStatus(
            @Parameter(description = "Fraud alert ID") @PathVariable Long id,
            @RequestBody @Valid UpdateAlertStatusRequest request) {
        return ResponseEntity.ok(
                fraudAlertService.updateAlertStatus(id, request.getStatus()));
    }

    @GetMapping("/stats")
    @Operation(
            summary = "Get fraud statistics",
            description = "Returns a summary of fraud alerts including totals by severity and by rule triggered"
    )
    public ResponseEntity<FraudStatsResponse> getStats() {
        return ResponseEntity.ok(fraudAlertService.getStats());
    }
}